import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { OBJLoader } from 'three/addons/loaders/OBJLoader.js';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
import { SVGRenderer } from 'three/addons/renderers/SVGRenderer.js';
import { SVGLoader } from 'three/addons/loaders/SVGLoader.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';
import { buildEmbeddableHtml } from './web-export.js';

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const stage = $('#stage');
const scene = new THREE.Scene();
scene.fog = new THREE.FogExp2(0x0d0e0c, .055);
const camera = new THREE.PerspectiveCamera(38, 1, .1, 100);
camera.position.set(4.2, 2.8, 5);
const renderer = new THREE.WebGLRenderer({ antialias:true, alpha:true, preserveDrawingBuffer:true });
renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setClearColor(0x0d0e0c,0); renderer.shadowMap.enabled=true;
renderer.outputColorSpace=THREE.SRGBColorSpace; stage.prepend(renderer.domElement);
const distortionShader={uniforms:{tDiffuse:{value:null},amount:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform sampler2D tDiffuse;uniform float amount;varying vec2 vUv;void main(){vec2 p=vUv*2.0-1.0;float r=dot(p,p);vec2 uv=.5+(p*(1.0+amount*r))*.5;if(uv.x<0.0||uv.x>1.0||uv.y<0.0||uv.y>1.0)gl_FragColor=vec4(0.05,0.055,0.045,1.0);else gl_FragColor=texture2D(tDiffuse,uv);}`};
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const distortionPass=new ShaderPass(distortionShader);composer.addPass(distortionPass);
const controls = new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.dampingFactor=.06;
const hemi=new THREE.HemisphereLight(0xe9f0d7,0x282f20,1.4); scene.add(hemi);
const key=new THREE.DirectionalLight(0xffffff,3.2); key.position.set(3,5,4); key.castShadow=true; scene.add(key);
const rim=new THREE.PointLight(0xd8ff45,24,12); rim.position.set(-3,1,-2); scene.add(rim);
const fill=new THREE.DirectionalLight(0xa7b8ff,1.1);fill.position.set(-4,2,-3);scene.add(fill);
const grid=new THREE.GridHelper(20,40,0x4b5140,0x292c25); grid.position.y=-1.45; scene.add(grid);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.ShadowMaterial({color:0x000000,opacity:.25})); floor.rotation.x=-Math.PI/2;floor.position.y=-1.44;floor.receiveShadow=true;scene.add(floor);

let root, backgroundRoot, playing=true, preset='orbit', elapsed=0, selectedFormat='gif', isDragging=false, dragStart=new THREE.Vector2();
const backgroundOffset=new THREE.Vector3();
let modelAssetPromise=Promise.resolve(null),backgroundAssetPromise=Promise.resolve(null),backgroundType='world';
const material=new THREE.MeshStandardMaterial({color:0xd8ff45,roughness:.28,metalness:.12,side:THREE.DoubleSide});
function makeDemo(){const geo=new THREE.TorusKnotGeometry(1, .34, 180, 24, 2, 3); const mesh=new THREE.Mesh(geo,material);mesh.castShadow=true;return mesh}
function installModel(obj){ if(root)scene.remove(root); root=obj; const box=new THREE.Box3().setFromObject(root), size=box.getSize(new THREE.Vector3()), center=box.getCenter(new THREE.Vector3()); root.position.sub(center); const max=Math.max(size.x,size.y,size.z)||1; root.scale.multiplyScalar(2.5/max); root.traverse(o=>{if(o.isMesh){o.material=material;o.castShadow=true;o.geometry.computeVertexNormals();o.userData.original=Float32Array.from(o.geometry.attributes.position.array)}}); scene.add(root); controls.target.set(0,0,0); alignBackgroundToModel(); }
function getModelCenter(){return root?new THREE.Box3().setFromObject(root).getCenter(new THREE.Vector3()):new THREE.Vector3()}
function alignBackgroundToModel(){if(backgroundRoot)backgroundRoot.position.copy(getModelCenter()).add(backgroundOffset)}
function clearBackground(){if(backgroundRoot){scene.remove(backgroundRoot);backgroundRoot.traverse?.(o=>{o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose()});backgroundRoot=null}backgroundType='none';backgroundAssetPromise=Promise.resolve(null);setBackgroundLabel('无背景')}
function setBackgroundLabel(name){$('#backgroundName').textContent=name;$('#backgroundLayerName').textContent=name;$$('.mini-action').forEach(b=>b.classList.remove('active'))}
function createWorldSphere(){clearBackground();backgroundType='world';const geo=new THREE.SphereGeometry(28,48,24);const mat=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color(0x27301d)},bottom:{value:new THREE.Color(0x090b09)}},vertexShader:`varying vec3 vPos;void main(){vPos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform vec3 top;uniform vec3 bottom;varying vec3 vPos;void main(){float h=smoothstep(-12.0,14.0,vPos.y);float glow=pow(max(0.0,1.0-abs(vPos.y)/20.0),4.0);gl_FragColor=vec4(mix(bottom,top,h)+vec3(.035,.05,.012)*glow,1.0);}`});backgroundRoot=new THREE.Mesh(geo,mat);backgroundRoot.name='Fixed world sphere';backgroundRoot.renderOrder=-10;scene.add(backgroundRoot);resetBackgroundTransform();setBackgroundLabel('World sphere');$('#worldBtn').classList.add('active')}
function fitBackgroundObject(obj){const box=new THREE.Box3().setFromObject(obj),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());obj.position.sub(center);const max=Math.max(size.x,size.y,size.z)||1;obj.scale.multiplyScalar(10/max);obj.traverse(o=>{if(o.isMesh){o.material=new THREE.MeshStandardMaterial({color:0x4b5145,roughness:.9,metalness:0,side:THREE.DoubleSide});o.castShadow=false;o.receiveShadow=false}});return obj}
function installBackground(obj,name){clearBackground();backgroundType='asset';backgroundRoot=new THREE.Group();backgroundRoot.name='Fixed background container';backgroundRoot.add(fitBackgroundObject(obj));scene.add(backgroundRoot);resetBackgroundTransform();setBackgroundLabel(name)}
function resetBackgroundTransform(){backgroundOffset.set(0,0,0);if(backgroundRoot){alignBackgroundToModel();backgroundRoot.scale.setScalar(1)}['X','Y','Z'].forEach(a=>$('#bg'+a).value=0);$('#bgScale').value=1;$('#bgScaleOut').textContent='1.00'}
function setBackgroundColor(value){if(!backgroundRoot)return;const color=new THREE.Color(value);backgroundRoot.traverse(o=>{if(!o.material)return;const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>{if(m.color)m.color.copy(color);if(m.uniforms?.top)m.uniforms.top.value.copy(color);if(m.uniforms?.bottom)m.uniforms.bottom.value.copy(color).multiplyScalar(.18)})});$('#bgColorHex').textContent=value.toUpperCase()}
function handleBackgroundFile(file){if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(!['svg','obj','fbx'].includes(ext))return alert('背景支持 SVG、OBJ 或 FBX 文件。');if(file.size>50*1024*1024)return alert('背景文件超过 50MB。');$('#loading').classList.add('show');const url=URL.createObjectURL(file),assetPromise=file.arrayBuffer().then(buffer=>({name:file.name,ext,buffer}));if(ext==='obj'||ext==='fbx'){const loader=ext==='obj'?new OBJLoader():new FBXLoader();loader.load(url,obj=>{installBackground(obj,file.name);backgroundAssetPromise=assetPromise;finish()},undefined,fail)}else{new SVGLoader().load(url,data=>{const group=new THREE.Group();data.paths.forEach(path=>{const mat=new THREE.MeshBasicMaterial({color:path.color||0x747b68,side:THREE.DoubleSide,depthWrite:false});SVGLoader.createShapes(path).forEach(shape=>group.add(new THREE.Mesh(new THREE.ShapeGeometry(shape),mat)))});group.scale.y*=-1;installBackground(group,file.name);backgroundAssetPromise=assetPromise;finish()},undefined,fail)}function finish(){$('#loading').classList.remove('show');URL.revokeObjectURL(url)}function fail(e){finish();alert('背景解析失败：'+e.message)}}
installModel(makeDemo());
createWorldSphere();
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);composer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()} new ResizeObserver(resize).observe(stage);
function updateModel(t){if(!root)return; if(playing){if(preset==='orbit')root.rotation.y+=Number($('#speed').value)*.018; if(preset==='camera'){const r=Number($('#zoom').value);camera.position.x=controls.target.x+Math.sin(t*.00035)*r;camera.position.z=controls.target.z+Math.cos(t*.00035)*r;camera.position.y=controls.target.y+2+Math.sin(t*.0002);camera.lookAt(controls.target)} if(preset==='deform'){const amp=Number($('#deform').value);root.traverse(o=>{if(!o.isMesh||!o.userData.original)return;const p=o.geometry.attributes.position,a=o.userData.original;for(let i=0;i<p.count;i++){const x=a[i*3],y=a[i*3+1],z=a[i*3+2];p.setXYZ(i,x+Math.sin(y*3+t*.003)*amp*.18,y,z+Math.cos(x*3+t*.0025)*amp*.18)}p.needsUpdate=true;o.geometry.computeVertexNormals()})}}}
function animate(t){requestAnimationFrame(animate);controls.update();updateModel(t);composer.render();if(playing){elapsed=(elapsed+1/60)%6;const pct=elapsed/6*100;$('#playhead').style.left=pct+'%';$('#trackFill').style.width=pct+'%';$('#timecode').textContent=`00:0${Math.floor(elapsed)}.${String(Math.floor(elapsed%1*100)).padStart(2,'0')}`}} requestAnimationFrame(animate);

function handleFile(file){if(!file)return;if(file.size>50*1024*1024)return alert('文件超过 50MB，请压缩后重试。');const ext=file.name.split('.').pop().toLowerCase();if(!['obj','fbx'].includes(ext))return alert('目前支持 OBJ 或 FBX 文件。');$('#loading').classList.add('show');const url=URL.createObjectURL(file),loader=ext==='obj'?new OBJLoader():new FBXLoader();modelAssetPromise=file.arrayBuffer().then(buffer=>({name:file.name,ext,buffer}));loader.load(url,obj=>{installModel(obj);$('#modelName').textContent=file.name;$('#modelMeta').textContent=`${(file.size/1024/1024).toFixed(1)} MB · ${ext.toUpperCase()}`;$('#layerName').textContent=file.name;$('#loading').classList.remove('show');URL.revokeObjectURL(url)},undefined,e=>{$('#loading').classList.remove('show');alert('模型解析失败：'+e.message);URL.revokeObjectURL(url)})}
$('#fileInput').onchange=e=>handleFile(e.target.files[0]);['dragenter','dragover'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.add('dragover')}));['dragleave','drop'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.remove('dragover')}));$('#dropzone').addEventListener('drop',e=>handleFile(e.dataTransfer.files[0]));
$('#backgroundInput').onchange=e=>handleBackgroundFile(e.target.files[0]);['dragenter','dragover'].forEach(n=>$('#backgroundDropzone').addEventListener(n,e=>{e.preventDefault();$('#backgroundDropzone').classList.add('dragover')}));['dragleave','drop'].forEach(n=>$('#backgroundDropzone').addEventListener(n,e=>{e.preventDefault();$('#backgroundDropzone').classList.remove('dragover')}));$('#backgroundDropzone').addEventListener('drop',e=>handleBackgroundFile(e.dataTransfer.files[0]));$('#worldBtn').onclick=createWorldSphere;$('#clearBgBtn').onclick=()=>{clearBackground();$('#clearBgBtn').classList.add('active')};
['X','Y','Z'].forEach(a=>$('#bg'+a).oninput=e=>{backgroundOffset[a.toLowerCase()]=Number(e.target.value);alignBackgroundToModel()});$('#bgScale').oninput=e=>{const value=Number(e.target.value);if(backgroundRoot)backgroundRoot.scale.setScalar(value);$('#bgScaleOut').textContent=value.toFixed(2)};$('#bgColor').oninput=e=>setBackgroundColor(e.target.value);$('#resetBgTransform').onclick=resetBackgroundTransform;
$$('.preset').forEach(b=>b.onclick=()=>{$$('.preset').forEach(x=>x.classList.remove('active'));b.classList.add('active');preset=b.dataset.preset;controls.enabled=preset!=='drag'});
renderer.domElement.addEventListener('pointerdown',e=>{if(preset==='drag'){isDragging=true;dragStart.set(e.clientX,e.clientY)}});window.addEventListener('pointerup',()=>isDragging=false);window.addEventListener('pointermove',e=>{if(isDragging&&root){root.position.x+=(e.clientX-dragStart.x)*.008;root.position.y-=(e.clientY-dragStart.y)*.008;dragStart.set(e.clientX,e.clientY);syncTransform()}});
function bindRange(id,out,digits=2){$(id).oninput=e=>$(out).textContent=Number(e.target.value).toFixed(digits)}bindRange('#speed','#speedOut');bindRange('#deform','#deformOut');bindRange('#zoom','#zoomOut',1);$('#zoom').addEventListener('input',e=>camera.position.setLength(Number(e.target.value)));$('#color').oninput=e=>{material.color.set(e.target.value);$('#colorHex').textContent=e.target.value.toUpperCase()};
bindRange('#lightIntensity','#lightIntensityOut',1);bindRange('#ambient','#ambientOut',1);$('#lightIntensity').addEventListener('input',e=>key.intensity=Number(e.target.value));$('#ambient').addEventListener('input',e=>hemi.intensity=Number(e.target.value));$('#lightColor').oninput=e=>{key.color.set(e.target.value);$('#lightColorHex').textContent=e.target.value.toUpperCase()};['X','Y','Z'].forEach(a=>$('#light'+a).oninput=e=>key.position[a.toLowerCase()]=Number(e.target.value));
const lightLooks={studio:{key:3.2,ambient:1.4,color:'#ffffff',pos:[3,5,4],fill:1.1,rim:24},dramatic:{key:6.2,ambient:.4,color:'#ffd2a0',pos:[-4,6,2],fill:.15,rim:38},neon:{key:2.4,ambient:.7,color:'#7cdcff',pos:[4,1,-3],fill:2.8,rim:55}};
function applyLightPreset(name){const p=lightLooks[name];key.intensity=p.key;hemi.intensity=p.ambient;key.color.set(p.color);key.position.set(...p.pos);fill.intensity=p.fill;rim.intensity=p.rim;$('#lightIntensity').value=p.key;$('#lightIntensityOut').textContent=p.key.toFixed(1);$('#ambient').value=p.ambient;$('#ambientOut').textContent=p.ambient.toFixed(1);$('#lightColor').value=p.color;$('#lightColorHex').textContent=p.color.toUpperCase();['X','Y','Z'].forEach((a,i)=>$('#light'+a).value=p.pos[i])}
$$('[data-light]').forEach(b=>b.onclick=()=>{$$('[data-light]').forEach(x=>x.classList.remove('active'));b.classList.add('active');applyLightPreset(b.dataset.light)});
$('#focalLength').oninput=e=>{camera.setFocalLength(Number(e.target.value));$('#focalOut').textContent=e.target.value+' mm'};$('#distortion').oninput=e=>{distortionPass.uniforms.amount.value=Number(e.target.value);$('#distortionOut').textContent=Number(e.target.value).toFixed(2)};['X','Y','Z'].forEach(a=>$('#focus'+a).oninput=e=>{controls.target[a.toLowerCase()]=Number(e.target.value);camera.lookAt(controls.target)});
const cameraLooks={studio:{pos:[4.2,2.8,5],target:[0,0,0],focal:50,distortion:0},closeup:{pos:[2.2,1.1,2.7],target:[0,.25,0],focal:85,distortion:-.12}};
function applyCameraPreset(name){const p=cameraLooks[name];camera.position.set(...p.pos);controls.target.set(...p.target);camera.setFocalLength(p.focal);distortionPass.uniforms.amount.value=p.distortion;$('#focalLength').value=p.focal;$('#focalOut').textContent=p.focal+' mm';$('#distortion').value=p.distortion;$('#distortionOut').textContent=p.distortion.toFixed(2);['X','Y','Z'].forEach((a,i)=>$('#focus'+a).value=p.target[i]);camera.lookAt(controls.target)}
$$('[data-camera]').forEach(b=>b.onclick=()=>{$$('[data-camera]').forEach(x=>x.classList.remove('active'));b.classList.add('active');applyCameraPreset(b.dataset.camera)});
function syncTransform(){if(!root)return;$('#posX').value=root.position.x.toFixed(2);$('#posY').value=root.position.y.toFixed(2);$('#posZ').value=root.position.z.toFixed(2)};['X','Y','Z'].forEach(a=>$('#pos'+a).oninput=e=>root.position[a.toLowerCase()]=Number(e.target.value));$('#scale').oninput=e=>root.scale.setScalar(Number(e.target.value));
$('#playBtn').onclick=$('#pauseBtn').onclick=()=>{playing=!playing;$('#playBtn').textContent=playing?'▶':'Ⅱ'};$('#resetBtn').onclick=()=>{root.rotation.set(0,0,0);root.position.set(0,0,0);applyCameraPreset('studio');syncTransform()};$('#randomBtn').onclick=()=>{['speed','deform','zoom'].forEach(id=>{const e=$('#'+id),v=Number(e.min)+Math.random()*(Number(e.max)-Number(e.min));e.value=v;e.dispatchEvent(new Event('input'))})};$('#gridBtn').onclick=e=>{grid.visible=!grid.visible;floor.visible=grid.visible;e.currentTarget.classList.toggle('active')};$('#fitBtn').onclick=()=>applyCameraPreset('studio');
$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.view;if(v==='front')camera.position.set(0,0,5);else if(v==='top')camera.position.set(0,5,.01);else camera.position.set(4.2,2.8,5);camera.lookAt(0,0,0)});
$('#track').onclick=e=>{elapsed=(e.offsetX/e.currentTarget.clientWidth)*6};
$('#exportBtn').onclick=()=>$('#exportDialog').showModal();$$('.export-option').forEach(b=>b.onclick=()=>{$$('.export-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedFormat=b.dataset.format;$('#exportConfirm').textContent=`开始导出 ${selectedFormat.toUpperCase()}`;const notes={gif:'GIF 将逐帧记录当前 3D 动效，导出过程可能需要几秒。',svg:'SVG 将以矢量路径保存当前视角的模型快照。',web:'WEB 将打包当前模型、背景和所有交互预设，生成只保留 3D 显示窗的嵌入式网页。'};$('#exportNote').textContent=notes[selectedFormat]});
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function exportWebPackage(){if(typeof JSZip==='undefined')return alert('网页打包器未加载，请检查网络连接。');const btn=$('#exportConfirm');btn.disabled=true;btn.textContent='正在收集场景预设...';try{const [modelAsset,backgroundAsset]=await Promise.all([modelAssetPromise,backgroundAssetPromise]);const modelPath=modelAsset?`assets/model.${modelAsset.ext}`:null,backgroundPath=backgroundAsset?`assets/background.${backgroundAsset.ext}`:null;const config={version:1,interaction:preset,motion:{speed:Number($('#speed').value),deform:Number($('#deform').value)},model:{asset:modelPath?{url:modelPath,ext:modelAsset.ext}:null,color:$('#color').value,position:root?getModelCenter().toArray():[0,0,0],scale:Number($('#scale').value)},background:{type:backgroundType,asset:backgroundPath?{url:backgroundPath,ext:backgroundAsset.ext}:null,color:$('#bgColor').value,position:backgroundRoot?backgroundRoot.position.toArray():[0,0,0],scale:Number($('#bgScale').value)},lights:{intensity:key.intensity,ambient:hemi.intensity,color:'#'+key.color.getHexString(),position:key.position.toArray(),fill:fill.intensity,rim:rim.intensity},camera:{position:camera.position.toArray(),target:controls.target.toArray(),focalLength:camera.getFocalLength(),distortion:Number($('#distortion').value),distance:Number($('#zoom').value)}};const zip=new JSZip();zip.file('index.html',buildEmbeddableHtml(config));if(modelAsset)zip.file(modelPath,modelAsset.buffer);if(backgroundAsset)zip.file(backgroundPath,backgroundAsset.buffer);zip.file('embed-example.html',`<!doctype html><meta charset="utf-8"><style>html,body{margin:0;height:100%;background:#111}.viewer{width:100%;height:100%;border:0}</style><iframe class="viewer" src="./index.html" title="MotionForge 3D"></iframe>`);zip.file('README.txt','MotionForge 实时交互包\n\n1. 将整个文件夹部署到任意静态网站。\n2. 直接访问 index.html 查看交互场景。\n3. 复制 embed-example.html 中的 iframe 到其他网页。\n4. 本包首次加载需要联网获取 Three.js。\n');btn.textContent='正在生成 ZIP...';const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}},meta=>btn.textContent=`正在打包 ${Math.round(meta.percent)}%`);download(blob,'motionforge-interactive-web.zip');$('#exportDialog').close()}catch(e){alert('网页包生成失败：'+e.message)}finally{btn.disabled=false;btn.textContent='开始导出 WEB'}}
function exportSVG(){const svgRenderer=new SVGRenderer();const scale=Number($('#quality').value);svgRenderer.setSize(800*scale,800*scale);svgRenderer.render(scene,camera);download(new Blob([new XMLSerializer().serializeToString(svgRenderer.domElement)],{type:'image/svg+xml'}),'motionforge-scene.svg')}
function exportGIF(){if(typeof GIF==='undefined')return alert('GIF 编码器未加载，请检查网络连接。');const btn=$('#exportConfirm');btn.textContent='正在渲染 0 / 48';btn.disabled=true;const gif=new GIF({workers:2,quality:8,width:800,height:800,workerScript:'https://cdn.jsdelivr.net/npm/gif.js.optimized@1.0.1/dist/gif.worker.js'});const oldSize=new THREE.Vector2();renderer.getSize(oldSize);renderer.setSize(800,800,false);composer.setSize(800,800);let frame=0;const capture=()=>{updateModel(frame*125);composer.render();gif.addFrame(renderer.domElement,{copy:true,delay:125});frame++;btn.textContent=`正在渲染 ${frame} / 48`;if(frame<48)setTimeout(capture,0);else{renderer.setSize(oldSize.x,oldSize.y,false);composer.setSize(oldSize.x,oldSize.y);gif.render()}};gif.on('finished',blob=>{download(blob,'motionforge-loop.gif');btn.disabled=false;btn.textContent='开始导出 GIF';$('#exportDialog').close()});capture()}
$('#exportConfirm').onclick=()=>selectedFormat==='svg'?exportSVG():selectedFormat==='web'?exportWebPackage():exportGIF();
