export function buildEmbeddableHtml(config){
  const data=JSON.stringify(config).replaceAll('<','\\u003c');
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MotionForge Interactive Scene</title>
<style>*{box-sizing:border-box}html,body,#motionforge-canvas{width:100%;height:100%;margin:0;overflow:hidden;background:#0d0e0c}#motionforge-canvas{display:block;touch-action:none}.loading{position:fixed;inset:0;display:grid;place-items:center;background:#0d0e0c;color:#d8ff45;font:11px monospace;letter-spacing:.12em}.loading.done{display:none}</style>
<script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/"}}</script></head>
<body><canvas id="motionforge-canvas" aria-label="MotionForge 3D interactive canvas"></canvas><div class="loading" id="loading">LOADING 3D SCENE</div>
<script type="module">
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
import {SVGLoader} from 'three/addons/loaders/SVGLoader.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
const C=${data},host=document.body,canvas=document.querySelector('#motionforge-canvas'),scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x0d0e0c,.055);
const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.fromArray(C.camera.position);camera.setFocalLength(C.camera.focalLength);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x0d0e0c,1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;
const distortionShader={uniforms:{tDiffuse:{value:null},amount:{value:C.camera.distortion}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform sampler2D tDiffuse;uniform float amount;varying vec2 vUv;void main(){vec2 p=vUv*2.0-1.0;float r=dot(p,p);vec2 uv=.5+(p*(1.0+amount*r))*.5;if(uv.x<0.0||uv.x>1.0||uv.y<0.0||uv.y>1.0)gl_FragColor=vec4(.05,.055,.045,1.0);else gl_FragColor=texture2D(tDiffuse,uv);}'};
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new ShaderPass(distortionShader));
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.fromArray(C.camera.target);controls.enabled=C.interaction!=='drag';
const hemi=new THREE.HemisphereLight(0xe9f0d7,0x282f20,C.lights.ambient);scene.add(hemi);const key=new THREE.DirectionalLight(C.lights.color,C.lights.intensity);key.position.fromArray(C.lights.position);scene.add(key);const fill=new THREE.DirectionalLight(0xa7b8ff,C.lights.fill);fill.position.set(-4,2,-3);scene.add(fill);const rim=new THREE.PointLight(0xd8ff45,C.lights.rim,12);rim.position.set(-3,1,-2);scene.add(rim);
const material=new THREE.MeshStandardMaterial({color:C.model.color,roughness:.28,metalness:.12,side:THREE.DoubleSide});let root;
function normalize(obj,size){const box=new THREE.Box3().setFromObject(obj),s=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());obj.position.sub(center);obj.scale.multiplyScalar(size/(Math.max(s.x,s.y,s.z)||1));return obj}
function installModel(obj){root=normalize(obj,2.5);root.position.fromArray(C.model.position);root.scale.multiplyScalar(C.model.scale);root.traverse(o=>{if(o.isMesh){o.material=material;o.userData.original=Float32Array.from(o.geometry.attributes.position.array);o.geometry.computeVertexNormals()}});scene.add(root)}
function loadAsset(asset,background=false){return new Promise((resolve,reject)=>{if(!asset)return resolve(null);if(asset.ext==='svg'){new SVGLoader().load(asset.url,d=>{const g=new THREE.Group();d.paths.forEach(p=>{const m=new THREE.MeshStandardMaterial({color:C.background.color,side:THREE.DoubleSide,roughness:.9});SVGLoader.createShapes(p).forEach(s=>g.add(new THREE.Mesh(new THREE.ShapeGeometry(s),m)))});g.scale.y*=-1;resolve(g)},undefined,reject)}else{const loader=asset.ext==='obj'?new OBJLoader():new FBXLoader();loader.load(asset.url,resolve,undefined,reject)}})}
function worldSphere(){const g=new THREE.SphereGeometry(28,48,24),color=new THREE.Color(C.background.color);return new THREE.Mesh(g,new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:color},bottom:{value:color.clone().multiplyScalar(.18)}},vertexShader:'varying vec3 vPos;void main(){vPos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 vPos;void main(){float h=smoothstep(-12.0,14.0,vPos.y);gl_FragColor=vec4(mix(bottom,top,h),1.0);}' }))}
async function init(){try{if(C.model.asset)installModel(await loadAsset(C.model.asset));else installModel(new THREE.Mesh(new THREE.TorusKnotGeometry(1,.34,180,24,2,3),material));if(C.background.type!=='none'){let bg=C.background.type==='world'?worldSphere():normalize(await loadAsset(C.background.asset,true),10);if(C.background.type!=='world')bg.traverse(o=>{if(o.isMesh)o.material=new THREE.MeshStandardMaterial({color:C.background.color,roughness:.9,side:THREE.DoubleSide})});const wrapper=new THREE.Group();wrapper.add(bg);wrapper.position.fromArray(C.background.position);wrapper.scale.setScalar(C.background.scale);scene.add(wrapper)}}finally{document.querySelector('#loading').classList.add('done')}}
let drag=false,last={x:0,y:0};renderer.domElement.addEventListener('pointerdown',e=>{if(C.interaction==='drag'){drag=true;last={x:e.clientX,y:e.clientY}}});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(drag&&root){root.position.x+=(e.clientX-last.x)*.008;root.position.y-=(e.clientY-last.y)*.008;last={x:e.clientX,y:e.clientY}}});
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);composer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);
let paused=false;window.MotionForgeCanvas={canvas,renderer,scene,camera,setInteraction(value){if(['orbit','drag','camera','deform'].includes(value)){C.interaction=value;controls.enabled=value!=='drag'}},play(){paused=false},pause(){paused=true},resize,setModelColor(value){material.color.set(value)},getPreset(){return structuredClone(C)}};
addEventListener('message',e=>{const m=e.data;if(!m||m.source!=='motionforge')return;if(m.action==='play')MotionForgeCanvas.play();if(m.action==='pause')MotionForgeCanvas.pause();if(m.action==='setInteraction')MotionForgeCanvas.setInteraction(m.value);if(m.action==='setModelColor')MotionForgeCanvas.setModelColor(m.value)});
function animate(t){requestAnimationFrame(animate);controls.update();if(!paused&&root){if(C.interaction==='orbit')root.rotation.y+=C.motion.speed*.018;if(C.interaction==='camera'){const r=C.camera.distance;camera.position.x=controls.target.x+Math.sin(t*.00035)*r;camera.position.z=controls.target.z+Math.cos(t*.00035)*r;camera.lookAt(controls.target)}if(C.interaction==='deform'){root.traverse(o=>{if(!o.isMesh||!o.userData.original)return;const p=o.geometry.attributes.position,a=o.userData.original;for(let i=0;i<p.count;i++){const x=a[i*3],y=a[i*3+1],z=a[i*3+2];p.setXYZ(i,x+Math.sin(y*3+t*.003)*C.motion.deform*.18,y,z+Math.cos(x*3+t*.0025)*C.motion.deform*.18)}p.needsUpdate=true;o.geometry.computeVertexNormals()})}}composer.render()}init().then(()=>dispatchEvent(new CustomEvent('motionforge-ready',{detail:window.MotionForgeCanvas})));animate(0);
</script></body></html>`;
}
